### ISSUE TITLE
Table of contents is broken

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-docs#313]
The table of contents plugin is broken, it does not load. We removed it for now so the page content at least takes the full width, but it should be bring back since it's very important for navigation.

> warning: Failed to load the plugin: docpad-plugin-tableofcontents at /Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad-plugin-tableofcontents
The error follows:

> SyntaxError: Setter must have exactly one formal parameter.
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:374:25)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad-plugin-tableofcontents/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad-plugin-tableofcontents/node_modules/jsdom/lib/jsdom/level3/core.js:1:83)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad-plugin-tableofcontents/node_modules/jsdom/lib/jsdom/level3/index.js:3:14)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad-plugin-tableofcontents/node_modules/jsdom/lib/jsdom.js:1:92)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at module.exports (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad-plugin-tableofcontents/out/tableofcontents.plugin.js:42:11)
  at PluginLoader.load (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/out/lib/plugin-loader.js:264:50)
  at /Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/out/lib/docpad.js:4304:25
  at PluginLoader.unsupported (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/out/lib/plugin-loader.js:207:5)
  at /Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/out/lib/docpad.js:4288:23
  at success (/Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/out/lib/plugin-loader.js:148:14)
  at /Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/out/lib/plugin-loader.js:181:18
  at /Users/joseph/Documents/Developement/cozycloud/dev-env/cozy-docs/cozy-docs/node_modules/docpad/node_modules/safefs/node_modules/graceful-fs/graceful-fs.js:78:16
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by clochix** [comment]
Have you tried upgrade Docpad to the latest version? The error happens in `cson` module, which seems to be quite old in the version we use.

**Comment by jsilvestre** [comment]
There are issues with docpad version / node version / node_modules version, so I didn't try it (it's a problem to build it automatically with rundeck if docpad is too recent) :-/
